"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--hm!#lk*69ew)o!#*7b+zc*ax!_genyqr_^i5k-5g5rfm-k*zs'

# Lee una variable de Render. Si no existe ('1'), usa True (para tu PC)
DEBUG = os.environ.get('DEBUG', '1') == '1'

# Le decimos en qué dominios confiamos
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'alexis-backend.onrender.com',       # Tu backend en Render
    'mi-protafolio-liard.vercel.app',  # Tu frontend en Vercel
]


# Application definition

INSTALLED_APPS = [
    # Apps de Django (ya existen)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',

    # Apps de Terceros (las que instalamos)
    'rest_framework',      # <-- Agrega esta (para la API)
    'corsheaders',         # <-- Agrega esta (para el "guardia de seguridad" CORS)

    # Mis Apps (las que creamos)
    'portafolio.apps.PortafolioConfig', # <-- Agrega esta (tu app)
    'chatbot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuración de Base de Datos (inteligente)
# Si Render nos da una 'DATABASE_URL', la usamos (PostgreSQL).
# Si no (en tu PC), usamos 'sqlite3'.
if 'DATABASE_URL' in os.environ:
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = 'static/'

# --- Configuración de Archivos Media (para tu CV) ---

# MEDIA_URL es la dirección web pública para ver los archivos
# (ej: http://localhost:8000/media/cv/mi_cv.pdf)
MEDIA_URL = '/media/'

# MEDIA_ROOT es la carpeta FÍSICA donde Django guardará los archivos
# (creará una carpeta 'media' en 'backend/')
MEDIA_ROOT = BASE_DIR / 'media'

# ... (debajo de MEDIA_ROOT)

# Configuración de archivos estáticos (para Whitenoise y Admin)
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Lista de "amigos" (orígenes) que tienen permiso para hablar con tu API
# 'http://localhost:5173' es la dirección estándar de React (Vite)
# Lista de "amigos" que pueden hablar con tu API
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173", # Tu React local
    "https://mi-protafolio-liard.vercel.app", # ¡Tu React en Vercel!
]