# Generated by Django 5.2.8 on 2025-11-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnologia',
            name='icon_name',
            field=models.CharField(default='FaQuestionCircle', max_length=100),
            preserve_default=False,
        ),
    ]
