# Generated by Django 5.2.8 on 2025-11-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_tecnologia_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnologia',
            name='categoria',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Base de Datos'), ('devops', 'DevOps/Producción'), ('other', 'Otra')], default='other', max_length=50),
        ),
    ]
