# Generated by Django 5.2.8 on 2025-11-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_tecnologia_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='cv',
        ),
        migrations.AddField(
            model_name='perfil',
            name='cv_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
